language: python

python:
  - "3.5"


install:
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql

before_script:
  - psql -c "CREATE USER test_user WITH PASSWORD 'postgres';" -U postgres
  - psql -c "CREATE DATABASE shoppinglist_test owner test_user;" -U postgres
  - psql -c "CREATE DATABASE shoppinglist owner test_user;" -U postgres
 

script:
  - coverage run --source=app -m py.test && coverage report
  - coveralls
after_sucess:
  - coveralls
